apiVersion: v1
kind: Namespace
metadata:
  labels:
    hello: all
  name: rabbit-demo
---
apiVersion: v1
kind: Service
metadata:
  name: calc-main-service
  namespace: rabbit-demo
spec:
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: calc-main
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: calc-main-deploy
  namespace: rabbit-demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: calc-main
  template:
    metadata:
      labels:
        app: calc-main
    spec:
      containers:
      - image: gcr.io/kuar-demo/kuard-amd64:blue
        name: LP-is-smelly
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$2
  labels:
    name: calc-main-ingress
  name: calc-main-ingress
  namespace: rabbit-demo
spec:
  rules:
  - host: kuard.micromicroservice.net
    http:
      paths:
      - backend:
          service:
            name: calc-main-service
            port:
              number: 80
        path: /
        pathType: Prefix
