apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: rabbit-demo-kustomization
  namespace: flux-system
spec:
  interval: 1m
  targetNamespace: rabbit-testing
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: "./k8s/calc-main/dev"
  prune: true
  postBuild:
    substitute:
      cluster_env: "dev"